// src/routes/sequences/index.svelte
<script lang="typescript" context="module">
	export async function preload(this: any, page: any, session: any) {
		const response: Response = await this.fetch("sequences.json");
		if (response.status == 200) {
			const sequences: SequenceInfo[] = await response.json();
			return { sequences };
		} else {
			this.error(404, "Couldn't load list of sequences");
		}
	}

	function codepoint(value: number): string {
		return "U+" + (value || 0).toString(16).padStart(4, "0").toUpperCase();
	}
</script>

<script lang="typescript">
	import OpenGraph from "../../components/OpenGraph.svelte";
	import type { SequenceInfo } from "server/Unicode";
	import StringBlob, { Encoding } from "model/StringBlob";

	export let sequences: SequenceInfo[];

	function createUrl(seq: SequenceInfo) {
		const string = StringBlob.stringDecode(Encoding.Utf8, seq.text);
		return `inspect/${string.urlEncode()}`;
	}
</script>

<style>
	.table {
		grid-template-columns: 1fr min-content;
	}
</style>

<OpenGraph
	title="Sequences - Unicode Visualizer"
	description="Browse the named sequences in Unicode." />

<h1>Browse Unicode Named Sequences</h1>

<div class="table">
	{#each sequences as sequence}
		<a href="sequences/{sequence.slug}">
			<div>{sequence.name}</div>
			<div>
				<code>{sequence.text}</code>
			</div>
		</a>
	{/each}
</div>

// src/components/Pages/Sequences.tsx
import React from "react";
import { fetchCompressedDatabase, Sequence } from "../../Unicode";
import { decimalToHex } from "../../Util";
import Table from "../Table";
import StringBlob, { Encoding } from "../../StringBlob";

enum Status {
  Loading,
  Loaded,
  Error
}

type State =
  | {
      status: Status.Loading;
    }
  | {
      status: Status.Loaded;
      sequences: Sequence[];
    }
  | {
      status: Status.Error;
      error: string;
    };

function createUrl(text: string) {
  const blob = StringBlob.stringDecode(Encoding.Utf16, text).urlEncode();
  return `/inspect/${blob}`;
}

export default class Sequences extends React.Component {
  state: State = {
    status: Status.Loading
  };

  render() {
    let content;
    switch (this.state.status) {
      case Status.Loading:
        content = <h3>Loading...</h3>;
        break;
      case Status.Error:
        content = <h3>Error: {this.state.error}</h3>;
        break;
      case Status.Loaded: {
        const sequences = this.state.sequences.map(sequence => ({
          link: createUrl(sequence.text),
          contents: [
            sequence.text,
            sequence.name,
            <code>
              {sequence.codepoints.map(code => decimalToHex(code, 4)).join(" ")}
            </code>
          ]
        }));
        const headings = ["Text", "Name", "Codepoints"];
        content = (
          <Table columns="6em 3fr 1fr" headings={headings} rows={sequences} />
        );
        break;
      }
    }

    return (
      <div className="App-content">
        <div className="App-contentContainer">
          <h2>Browse Unicode Named Sequences</h2>
          {content}
        </div>
      </div>
    );
  }

  async fetch() {
    try {
      const database = await fetchCompressedDatabase();
      const sequences = database.getSequenceInfo();
      this.setState({
        status: Status.Loaded,
        sequences
      });
    } catch (e) {
      console.log(e);
      this.setState({
        status: Status.Error,
        error: e.toString()
      });
    }
  }

  componentDidMount() {
    this.fetch();
  }
}
